FROM node:23.11.0-slim as builder

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npm run build
RUN npm prune --production

# final stage
FROM node:22-alpine
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY package.json .
EXPOSE 3000
ENV NODE_ENV=production
CMD [ "node", "./build" ]
