services:
  backend:
    image: teddy-hospital-backend
    container_name: teddy-hosptial-backend
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile-prod
    ports:
      - "8000:8000"

  frontend:
    image: teddy-hospital-frontend
    container_name: teddy-hospital-frontend
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile-prod
    expose: 
      - 3000
    depends_on:
      - backend


  nginx:
    image: nginx
    container_name: "teddy-hosptial-nginx"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ${CERTIFICATE_LOCATION}:/ssl_cert.pem
      - ${CERTIFICATE_KEY_LOCATION}:/ssl_key.pem
    ports:
      - "80:80"
      - "443:443"
    env_file: ".env"
    depends_on:
      - backend
      - frontend
    command: []
