services:
  backend:
    image: teddy-hospital-backend
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile-prod
    ports:
      - "8000:8000"

  frontend:
    image: teddy-hospital-frontend
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile-prod
    ports:
      - "80:3000"
      - "443:3000"
    depends_on:
      - backend
