FROM python:3.12-slim

# Set workdir
WORKDIR /app

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
# Install dependencies
COPY ./requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY . .
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 libgl1 -y

# Run FastAPI with uvicorn
CMD ["fastapi", "run", "main.py", "--host", "0.0.0.0", "--port", "8000"]
